### ISSUE TITLE
Kategoriesuche kaputt

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/fablab-android#1]
Feature ist z.Z. komplett nutzlos, denn man kann keine Unterkategorien wählen, und die obersten Kategorien sind Müll-Einträge

**Comment by vale** [comment]
Bitte den dazu passenden Branch / Pull request verlinken
TODO Androiduser bitte testen

**Comment by sedrubal** [comment]
Es ist der commit 2faec74 .

@Phyxtra: vllt. wären branches und pull requests für solche Dinge schöner und übersichtlicher...

**Comment by Phyxtra** [comment]
Sorry, aber ich habe noch nie was mit Pullrequests gemacht. Was ist so schlimm an normalen Commits? 
@vale Bitte auch von dir eine Erklärung, was du damit meinst. Und kann man den Fall nicht trotzdem schließen, er ist ja gefixt. Nur weil noch nicht getestet, heißt das ja nicht dass er noch offen sein muss?

**Comment by sedrubal** [comment]
Da muss man einfach bissl rum probieren, dann versteht man das ganz gut...

Üblicherweise macht man lokal einen branch

``` sh
git branch fix_cathegories
git checkout fix_cathegories
```

...bastelt herum und committed. Dann kann man den branch nach github pushen und in der Weboberfläche auf pull request erstellen clicken (das ist dann recht schön gemacht).

Dann ist das wie ein neuer issue, bei dem dann jeder seinen Senf abgeben kann und jeder kanns dann testen und wenn genug geflamed wurde, kann man den dann mergen (wenn man Glück hat, ist das ein klick in der web ui).

Denn issue schlieszt man auch erst dann, wenn alle zufrieden sind. Weil vllt. findest du so ok, aber andere könnten noch gute Einwände und Verbesserungsvorschläge haben... Dann könnte man noch weitere commits an den branch dran hängen und die erscheinen automatisch im pull request...

**Comment by vale** [comment]
Naja eigentlich würde man mit dem Pullrequest die Möglichkeit zum Testen vor dem merge geben. Das hätte damit den Vorteil, dass man keinen ungetesteten Code in den master übernimmt. Wenn man einen Issue schließt sollte man dazu aber zumindest den commit verlinken. @sedrubal danke dafür
@jneureuther empfiehlt http://nvie.com/posts/a-successful-git-branching-model/ zum Einlesen in den Umgang mit Branches

**Comment by Phyxtra** [comment]
Werd ich mir mal zu Herzen nehmen. Da ich nun aber einige Klausuren habe, müsst ihr erstmal mit normalen Commits klarkommen, sorry. Und vielen Dank @sedrubal für die Erklärung!

Ich muss dazu sagen, die Kategorieübersicht stammt nicht von mir. Wenn ich Zeit habe wird die komplett neu: Produktsuche und Kateogieren sind dann eine "Ansicht" in Android, nicht zwei. Kein Treeview, sondern Kacheln, um das ganze intuitiver zu machen. Damit ist dann die Kategorieübersicht vollintegriert in den Flow der App. Das dauert allerdings noch ein wenig, somit ist dies hier nur ein Fix des Problems, aber eh keine komplette Lösung.

**Comment by sedrubal** [comment]
Cool :+1:

**Comment by patkan** [comment]
Ohne mir den Commit jetzt genau angeschaut zu haben: Ein Pseudo-Fix wäre ja auch fürs erste mal alle "kaputten" Features abzuschalten. ;-)
