### ISSUE TITLE
APP ignoriert Drehsperre

### ISSUE THREAD

**Issue by patkan** [fau-fablab/fablab-android#12]
Ich weiß nicht genau wie man das nennt, aber auf Android kann man das Wechseln in landscape durch kippen sperren.
Die APP ignoriert diese Einstellung aber und dreht sich sowohl mit gesperrter Drehung und ohne.
Kann das jemand reproduzieren oder ist das nur an meinem gerät so?

**Comment by Phyxtra** [comment]
Hat mich auch schon immer genervt, ich war das nicht. Aber ich stell das bald um, danke für den Hinweis, der Punkt ist schon lang auf meiner Todo Liste

**Comment by patkan** [comment]
Top!

**Comment by Phyxtra** [comment]
Ist wohl eines der Libraries... Selbst ein force für portrait wird ignoriert. Ich suche weiter

**Comment by patkan** [comment]
Nur aus Neugierde: fixed oder wontfix?

**Comment by Phyxtra** [comment]
Schon bei letztem Release fixed. Hatte vergessen, es hier zu notieren.
