### ISSUE TITLE
Remove URL to newsfeed

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/fablab-android#17]
I'd find it great if the URL to a newsfeed wouldn't be displayed at the bottom of the view but if one can click on the title to open the feed in a browser.

**Comment by patkan** [comment]
Or maybe use the share-mechanism for the newsfeed link.
I don't know if there is a standard on android for newsfeed-links.

**Comment by sedrubal** [comment]
Ah yes, that's even better. We could remove the doorstate in this view (like it is in product search view) and add a share button to the bat at the top.

**Comment by Phyxtra** [comment]
Done.
