### ISSUE TITLE
App-Server Umstellung

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/fablab-android#2]
- Es soll app.fablab.fau.de verwendet werden.
- ~~Zwischenzustand (muss nicht unbedingt funktionieren, wäre aber gut): Das leitet zur Zeit auf die amazonaws Instanz um, weshalb das Zertifikat evtl nicht geht.~~
- Endzustand (muss wieder funktionieren, Release gleichzeitig mit Umstellung des Kassenterminals): app.fablab.fau.de mit neuem Zertifikat verwenden
- [ ] herausfinden und dokumentieren wie man ein neues Zertifikat in den truststore bringt
- [ ] sobald zukünftiges Zertifikat für app.fablab.fau.de vorhanden, dieses einbauen
- [ ] zum abgestimmten Zeitpunkt Release anstoßen

~~Ideal wäre natürlich eine Lösung, die app.fablab.fau.de verwendet und sowohl das alte als auch das neue Zertifikat akzeptiert, obwohl das alte evtl nen falschen Hostname hat. (Worauf ist das Pinning? Public Key oder gesamtes Zertifikat? Wenn nur auf den Key, könnten wir sogar das Ganze umsetzen, indem einfach nur der Hostname in der App geändert wird. Das muss man ausprobieren.)~~

**Comment by patkan** [comment]
Hi, nur als Anmerkung: Es gibt auf Android keine Releases die sofort auf allen Geräten wären. Der Google entscheidet, wann was wo deployed wird.
Ergo wäre der Optimalfall wenn der Zwischenstand auch funktioniert. Bevor das Gehampel und Aufwand wird, ist es vermutlich aber besser es einfach trotzdem zu machen und zu hoffen, dass das Release dann möglichst schnell verteilt wird. ;-)

**Comment by patkan** [comment]
Eventuell ist das hilfreich: http://www.thoughtcrime.org/blog/authenticity-is-broken-in-ssl-but-your-app-ha/
So wie es aussieht ist kein keystore eingecheckt im repository. Will man das? Wie macht man releases?

**Comment by patkan** [comment]
Ah, hier liegt der truststore: https://github.com/fau-fablab/fablab-android/blob/master/app/src/main/res/raw/fablab_dev_truststore

**Comment by mgmax** [comment]
So, wie siehts aus? app.fablab.fau steht, ich würde eine Hauruck-Umstellung vorschlagen, also einfach die App auf den neuen Server ändern, Release machen (Pullrequest gegen FAU-Inf2 und denen ne Mail schreiben) und fertig. Wenn es zwischendrin nicht geht, ist das auch egal.

**Comment by patkan** [comment]
Wäre ich auch dafür. Ich habe versucht mich in die toolchain einzuarbeiten, allerdings nicht recht doku gefunden und nicht alle Fehler los zu bekommen.
Muss also jemand mit Ahnung übernehmen.

**Comment by sedrubal** [comment]
Der Andreas vom Lehrstuhl meinte:
- für den Android Release müssen wir ihm eig. nur den Commit Hash oder den Tag Namen schicken (und das Repo, nicht dass er in FAU-Inf2/fablab-android sucht) und wenn sie im Lehrstuhl den Release Key wieder aufgetrieben haben, dann machen sie das.
- für iOS ist das ganze komplizierter. Aber da meinte wohl auch irgendwer (hab den Namen vergessen), dass er sich drum kümmert. Also das werden die dann unter sich aus machen...

**Comment by sebhaub** [comment]
Da ihr jetzt kein self-signed Zertifikat mehr verwendet, kann der custom-truststore komplett entfernt werden.

**Comment by sedrubal** [comment]
Möchte man das sicherheitshalber nicht trdm pinnen?

**Comment by mgmax** [comment]
Wir brauchen hier keine App bauen, die deinen uninteressanten Warenkorb 
mit mehr Sicherheit überträgt als deine Emails :-)

**Comment by sebhaub** [comment]
Ich denke pinning könnt ihr getrost auf eine "nice to have" Liste setzen für eure Zwecke :-)

**Comment by Phyxtra** [comment]
@sebhaub

Kannst du mir auf meine Mail antworten?

**Comment by mgmax** [comment]
(siehe Pullrequest #14)

**Comment by mgmax** [comment]
mit ef55273c59551845147d2f61b6c44ac6e3f823d0 erledigt
