### ISSUE TITLE
Use FabLab Travis

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/fablab-android#7]
I don't know if we have to configure Travis (adding env vars, ....). If so, we have to do this...

And then we have to change the build badge URL in README.md to the new Travis URL.

**Comment by patkan** [comment]
mgmax: Beim Travis muss man aufpassen, ob das Release dann noch geht... Das läuft ja weiter über den Lehrstuhl

--> We have to document how exactly the release process works in order to not disturb it.
